apiVersion: v1
data:
  cadvisor-scrape-config.yaml: LSBqb2JfbmFtZTogY2Fkdmlzb3IKICBzdGF0aWNfY29uZmlnczoKICAtIHRhcmdldHM6CiAgICAtIGNhZHZpc29yOjgwODAKICBtZXRyaWNfcmVsYWJlbF9jb25maWdzOgogIC0gYWN0aW9uOiBsYWJlbGRyb3AKICAgIHJlZ2V4OiBjb250YWluZXIKICAtIGFjdGlvbjogbGFiZWxkcm9wCiAgICByZWdleDogbmFtZXNwYWNlCiAgLSBhY3Rpb246IGxhYmVsZHJvcAogICAgcmVnZXg6IHBvZAogIC0gYWN0aW9uOiBsYWJlbG1hcAogICAgcmVnZXg6IGNvbnRhaW5lcl9sYWJlbF9hcHAKICAgIHJlcGxhY2VtZW50OiBjb250YWluZXIKICAtIGFjdGlvbjogbGFiZWxtYXAKICAgIHJlZ2V4OiBjb250YWluZXJfbGFiZWxfaW9fa3ViZXJuZXRlc19wb2RfbmFtZQogICAgcmVwbGFjZW1lbnQ6IHBvZAogIC0gYWN0aW9uOiBsYWJlbG1hcAogICAgcmVnZXg6IGNvbnRhaW5lcl9sYWJlbF9pb19rdWJlcm5ldGVzX3BvZF9uYW1lc3BhY2UKICAgIHJlcGxhY2VtZW50OiBuYW1lc3BhY2UK
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
  namespace: monitoring
