- job_name: cadvisor
  static_configs:
  - targets:
    - cadvisor:8080
  metric_relabel_configs:
  - action: labeldrop
    regex: container
  - action: labeldrop
    regex: namespace
  - action: labeldrop
    regex: pod
  - action: labelmap
    regex: container_label_app
    replacement: container
  - action: labelmap
    regex: container_label_io_kubernetes_pod_name
    replacement: pod
  - action: labelmap
    regex: container_label_io_kubernetes_pod_namespace
    replacement: namespace
