apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: stackrox
spec:
  serviceAccountName: prometheus
  podMonitorSelector:
    matchLabels:
      app: rhacs
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false